app_name = "college_template"
app_title = "College Template"
app_publisher = "Bizaxl"
app_description = "College ERP Customizations - Doctypes, Scripts, Reports & Dashboard"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "info@bizaxl.com"
app_license = "MIT"

# App dependencies for Frappe v15
# Education and LMS are separate apps in v15, must be installed first
app_dependencies = ["education", "lms"]

# Fixtures - installed via bench install-app
fixtures = [
    "Client Script",
    "Server Script",
    "Notification",
    "Report",
    "Number Card",
    "Dashboard Chart",
    "Event Certificate",
    "Event Feedback",
    "Event Document",
    "Event Gallery",
    "Event Expense",
    "Event Sponsor",
    "Event Winner",
    "Student Club",
    "College Event",
    "Event Budget",
    "Event Committee",
    "Event Attendance",
    "Event Registration",
    "Academic Calendar",
    "Academic Calendar Event",
    "Scholarship Verification",
    "Scholarship Verification Item",
    "Scholarship Renewal",
    "Scholarship Payment",
    "Scholarship Sanction",
    "Scholarship Application",
    "Scholarship Approval Log",
    "Scholarship Recommendation Log",
    "Scholarship Application Document",
    "Scholarship Scheme",
    "Alumni Donation",
    "Alumni Mentorship",
    "Alumni Event Registration",
    "Alumni Event",
    "Alumni Achievement",
    "Alumni Higher Education",
    "Alumni Employment",
    "Generate Alumni",
    "Generate Alumni Row",
    "Alumni",
    "Placement Drive Schedule",
    "Placement Offer",
    "Placement Registration",
    "Placement Drive",
    "Placement Company",
    "Placement Round Detail",
    "Placement Drive Program",
    "Exam Attendance",
    "Hall Allocation",
    "Hall Allocation Student",
    "Exam Schedule",
    "Exam Hall",
    "Course Registration Detail",
    "Course Registration",
    "Course Registration Window",
    "Student Promotion Detail",
    "Student Promotion",
    "Promotion Rule",
    "Fee Payment Entry",
    "Fee Payment Entry Reference",
    "Fee Head",
    "Promote Students",
    "Generate Student Fees",
    "Student Fee Assignment",
    "Student Fee Structure",
    "Student Fee Invoice Item",
    "Student Fee Structure Item",
    "Academic Enrollment",
    "Semester",
    "Section",
    "Academic Batch",
    "Admission Fee Structure Item",
    "Admission Fee Invoice Item",
    "Admission Program Enrollment",
    "Admission Student",
    "Eligibility Check",
    "Eligibility Rule Item",
    "Document Verification",
    "Document Verification Item",
    "Applicant Document",
    "Applicant Education",
    "Admission Enquiry",
    "Admission Enquiry Follow Up",
    "Admission Opening",
    "Admission Opening Eligibility",
    "Admission Opening Document",
    "Admission Opening Program",
    "Admission Marketing Activity",
    "Admission Campaign Program",
    "Admission Campaign",
    "Hall ticket",
    "Hall Ticket Subject",
    "LMS Batch Enrollment",
    "LMS Program Member",
    "LMS Program Course",
    "LMS Assessment",
    "Batch Course",
    "LMS Batch",
    "LMS Course",
    "LMS Quiz Submission",
    "LMS Quiz",
    "Course Lesson",
    "Course Chapter",
    "Print Heading"
]

# DocType JS
doctype_js = {}

# Boot info
before_tests = "college_template.install.before_tests"
